<template lang="pug">
div
  Mouse
  nuxt(ref="page")
  Loading(v-if="!isLoaded" :roundedPercentage="roundedPercentage" :percentage="percentage" ref="loading")
</template>

<script>
import Mouse from '~/components/Mouse'
import Loading from '~/components/Loading'

export default {
  data() {
    return {
      x: 0,
      y: 0,
      roundedPercentage: 0,
      percentage: 0,
      isLoaded: false,
      date: null,
      step: 1
    }
  },
  created() {
    this.date = new Date()
  },
  components: {
    Mouse,
    Loading
  },
  methods: {
    onProgress(event) {
      const elapsed = (new Date() - this.date)
      const percentage = !isNaN(event.loaded) ? Math.round(event.loaded * 100) : 100

      this.percentage = percentage

      if (elapsed > 1000) {
        this.date = new Date()
        this.roundedPercentage = Math.min(25 * this.step, percentage)
        if (this.roundedPercentage === 25 * this.step) this.step++
      }

      if (percentage === 100 && this.roundedPercentage < 100) window.requestAnimationFrame(this.onProgress)
      else {
        window.cancelAnimationFrame(this.onProgress)
        this.onComplete(event)
      }
    },
    onComplete(event) {
      if (this.roundedPercentage === 100) setTimeout(() => {
        if (this.$refs.loading) this.$refs.loading.$el.classList.add('is-hidden')
        setTimeout(() => {
          if (this.$refs.page.$route.name.includes('projects-')) document.body.classList.add('is-active')
          this.isLoaded = true
        }, 1500)
      }, 1500)
    }
  },
  mounted() {
    if (this.$refs.page.$route.name === null) this.isLoaded = true

    const path = '/_nuxt/static/images/'
    const queue = new createjs.LoadQueue()

    queue.on('progress', this.onProgress)
    queue.on('complete', this.onComplete)

    queue.loadManifest([
      `${path}About/circle/circle_0.png`,
      `${path}About/circle/circle_1.png`,
      `${path}About/circle/circle_2.png`,
      `${path}About/circle/circle_3.png`,
      `${path}About/circle/circle_4.png`,
      `${path}About/circle/circle_5.png`,
      `${path}About/circle/circle_6.png`,
      `${path}About/circle/circle_7.png`,
      `${path}About/circle/circle_8.png`,
      `${path}About/circle/circle_9.png`,
      `${path}About/circle/circle_10.png`,
      `${path}About/circle/circle_12.png`,
      `${path}About/circle/circle_12.png`,
      `${path}About/circle/circle_13.png`,
      `${path}About/circle/circle_14.png`,
      `${path}About/circle/circle_15.png`,
      `${path}About/circle/circle_16.png`,
      `${path}About/circle/circle_17.png`,
      `${path}About/circle/circle_18.png`,
      `${path}About/circle/circle_19.png`,
      `${path}About/circle.png`,
      `${path}About/circle_back.png`,
      `${path}About/circle_front.png`,
      `${path}About/pentagone/pentagone_0.png`,
      `${path}About/pentagone/pentagone_1.png`,
      `${path}About/pentagone/pentagone_2.png`,
      `${path}About/pentagone/pentagone_3.png`,
      `${path}About/pentagone/pentagone_4.png`,
      `${path}About/pentagone/pentagone_5.png`,
      `${path}About/pentagone/pentagone_6.png`,
      `${path}About/pentagone/pentagone_7.png`,
      `${path}About/pentagone/pentagone_8.png`,
      `${path}About/pentagone/pentagone_9.png`,
      `${path}About/pentagone/pentagone_10.png`,
      `${path}About/pentagone/pentagone_12.png`,
      `${path}About/pentagone/pentagone_12.png`,
      `${path}About/pentagone/pentagone_13.png`,
      `${path}About/pentagone/pentagone_14.png`,
      `${path}About/pentagone/pentagone_15.png`,
      `${path}About/pentagone/pentagone_16.png`,
      `${path}About/pentagone/pentagone_17.png`,
      `${path}About/pentagone/pentagone_18.png`,
      `${path}About/pentagone/pentagone_19.png`,
      `${path}About/pentagone.png`,
      `${path}About/pentagone_back.png`,
      `${path}About/pentagone_front.png`,
      `${path}About/square/square_0.png`,
      `${path}About/square/square_1.png`,
      `${path}About/square/square_2.png`,
      `${path}About/square/square_3.png`,
      `${path}About/square/square_4.png`,
      `${path}About/square/square_5.png`,
      `${path}About/square/square_6.png`,
      `${path}About/square/square_7.png`,
      `${path}About/square/square_8.png`,
      `${path}About/square/square_9.png`,
      `${path}About/square/square_10.png`,
      `${path}About/square/square_12.png`,
      `${path}About/square/square_12.png`,
      `${path}About/square/square_13.png`,
      `${path}About/square/square_14.png`,
      `${path}About/square/square_15.png`,
      `${path}About/square/square_16.png`,
      `${path}About/square/square_17.png`,
      `${path}About/square/square_18.png`,
      `${path}About/square/square_19.png`,
      `${path}About/square.png`,
      `${path}About/square_back.png`,
      `${path}About/square_front.png`,
      `${path}About/triangle/triangle_0.png`,
      `${path}About/triangle/triangle_1.png`,
      `${path}About/triangle/triangle_2.png`,
      `${path}About/triangle/triangle_3.png`,
      `${path}About/triangle/triangle_4.png`,
      `${path}About/triangle/triangle_5.png`,
      `${path}About/triangle/triangle_6.png`,
      `${path}About/triangle/triangle_7.png`,
      `${path}About/triangle/triangle_8.png`,
      `${path}About/triangle/triangle_9.png`,
      `${path}About/triangle/triangle_10.png`,
      `${path}About/triangle/triangle_12.png`,
      `${path}About/triangle/triangle_12.png`,
      `${path}About/triangle/triangle_13.png`,
      `${path}About/triangle/triangle_14.png`,
      `${path}About/triangle/triangle_15.png`,
      `${path}About/triangle/triangle_16.png`,
      `${path}About/triangle/triangle_17.png`,
      `${path}About/triangle/triangle_18.png`,
      `${path}About/triangle/triangle_19.png`,
      `${path}About/triangle.png`,
      `${path}About/triangle_back.png`,
      `${path}About/triangle_front.png`,

      `${path}BuddyBuddy/Animation.gif`,
      `${path}BuddyBuddy/Banner_Screenshots.png`,
      `${path}BuddyBuddy/Branding.png`,
      `${path}BuddyBuddy/Computer.png`,
      `${path}BuddyBuddy/Home.png`,
      `${path}BuddyBuddy/Laptop.png`,
      `${path}BuddyBuddy/Mobile_1.png`,
      `${path}BuddyBuddy/Mobile_2.png`,
      `${path}BuddyBuddy/Mobile_3.png`,
      `${path}BuddyBuddy/Mobile_4.png`,
      `${path}BuddyBuddy/Screen_1.png`,
      `${path}BuddyBuddy/Screen_2.png`,
      `${path}BuddyBuddy/Screen_3.png`,

      `${path}Error/circle.png`,
      `${path}Error/pentagone.png`,
      `${path}Error/square.png`,
      `${path}Error/triangle.png`,

      `${path}Home/Gaetan-cropped.png`,
      `${path}Home/Gaetan.png`,
      `${path}Home/circle/circle_0.png`,
      `${path}Home/circle/circle_1.png`,
      `${path}Home/circle/circle_2.png`,
      `${path}Home/circle/circle_3.png`,
      `${path}Home/circle/circle_4.png`,
      `${path}Home/circle/circle_5.png`,
      `${path}Home/circle/circle_6.png`,
      `${path}Home/circle/circle_7.png`,
      `${path}Home/circle/circle_8.png`,
      `${path}Home/circle/circle_9.png`,
      `${path}Home/circle/circle_10.png`,
      `${path}Home/circle/circle_12.png`,
      `${path}Home/circle/circle_12.png`,
      `${path}Home/circle/circle_13.png`,
      `${path}Home/circle/circle_14.png`,
      `${path}Home/circle/circle_15.png`,
      `${path}Home/circle/circle_16.png`,
      `${path}Home/circle/circle_17.png`,
      `${path}Home/circle/circle_18.png`,
      `${path}Home/circle/circle_19.png`,
      `${path}Home/circle.png`,
      `${path}Home/pentagone/pentagone_0.png`,
      `${path}Home/pentagone/pentagone_1.png`,
      `${path}Home/pentagone/pentagone_2.png`,
      `${path}Home/pentagone/pentagone_3.png`,
      `${path}Home/pentagone/pentagone_4.png`,
      `${path}Home/pentagone/pentagone_5.png`,
      `${path}Home/pentagone/pentagone_6.png`,
      `${path}Home/pentagone/pentagone_7.png`,
      `${path}Home/pentagone/pentagone_8.png`,
      `${path}Home/pentagone/pentagone_9.png`,
      `${path}Home/pentagone/pentagone_10.png`,
      `${path}Home/pentagone/pentagone_12.png`,
      `${path}Home/pentagone/pentagone_12.png`,
      `${path}Home/pentagone/pentagone_13.png`,
      `${path}Home/pentagone/pentagone_14.png`,
      `${path}Home/pentagone/pentagone_15.png`,
      `${path}Home/pentagone/pentagone_16.png`,
      `${path}Home/pentagone/pentagone_17.png`,
      `${path}Home/pentagone/pentagone_18.png`,
      `${path}Home/pentagone/pentagone_19.png`,
      `${path}Home/pentagone.png`,
      `${path}Home/square/square_0.png`,
      `${path}Home/square/square_1.png`,
      `${path}Home/square/square_2.png`,
      `${path}Home/square/square_3.png`,
      `${path}Home/square/square_4.png`,
      `${path}Home/square/square_5.png`,
      `${path}Home/square/square_6.png`,
      `${path}Home/square/square_7.png`,
      `${path}Home/square/square_8.png`,
      `${path}Home/square/square_9.png`,
      `${path}Home/square/square_10.png`,
      `${path}Home/square/square_12.png`,
      `${path}Home/square/square_12.png`,
      `${path}Home/square/square_13.png`,
      `${path}Home/square/square_14.png`,
      `${path}Home/square/square_15.png`,
      `${path}Home/square/square_16.png`,
      `${path}Home/square/square_17.png`,
      `${path}Home/square/square_18.png`,
      `${path}Home/square/square_19.png`,
      `${path}Home/square.png`,
      `${path}Home/triangle/triangle_0.png`,
      `${path}Home/triangle/triangle_1.png`,
      `${path}Home/triangle/triangle_2.png`,
      `${path}Home/triangle/triangle_3.png`,
      `${path}Home/triangle/triangle_4.png`,
      `${path}Home/triangle/triangle_5.png`,
      `${path}Home/triangle/triangle_6.png`,
      `${path}Home/triangle/triangle_7.png`,
      `${path}Home/triangle/triangle_8.png`,
      `${path}Home/triangle/triangle_9.png`,
      `${path}Home/triangle/triangle_10.png`,
      `${path}Home/triangle/triangle_12.png`,
      `${path}Home/triangle/triangle_12.png`,
      `${path}Home/triangle/triangle_13.png`,
      `${path}Home/triangle/triangle_14.png`,
      `${path}Home/triangle/triangle_15.png`,
      `${path}Home/triangle/triangle_16.png`,
      `${path}Home/triangle/triangle_17.png`,
      `${path}Home/triangle/triangle_18.png`,
      `${path}Home/triangle/triangle_19.png`,
      `${path}Home/triangle.png`,

      `${path}Menu/buddy-buddy.png`,
      `${path}Menu/personal.png`,
      `${path}Menu/pocketcare.png`,
      `${path}Menu/tesla.png`,

      `${path}Mouse/more.png`,
      `${path}Mouse/next.png`,

      `${path}Pocketcare/Banner_Inscription.png`,
      `${path}Pocketcare/Onboarding_1.png`,
      `${path}Pocketcare/Onboarding_2.png`,
      `${path}Pocketcare/Onboarding_3.png`,
      `${path}Pocketcare/Phone_1.gif`,
      `${path}Pocketcare/Phone_2.gif`,
      `${path}Pocketcare/Screens.png`,

      `${path}Projects/buddy-buddy/buddy-buddy_0.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_1.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_2.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_3.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_4.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_5.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_6.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_7.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_8.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_9.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_10.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_12.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_12.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_13.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_14.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_15.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_16.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_17.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_18.png`,
      `${path}Projects/buddy-buddy/buddy-buddy_19.png`,
      `${path}Projects/buddy-buddy.png`,
      `${path}Projects/buddy-buddy_back.png`,
      `${path}Projects/buddy-buddy_extra.png`,
      `${path}Projects/buddy-buddy_front.png`,
      `${path}Projects/personal/personal_0.png`,
      `${path}Projects/personal/personal_1.png`,
      `${path}Projects/personal/personal_2.png`,
      `${path}Projects/personal/personal_3.png`,
      `${path}Projects/personal/personal_4.png`,
      `${path}Projects/personal/personal_5.png`,
      `${path}Projects/personal/personal_6.png`,
      `${path}Projects/personal/personal_7.png`,
      `${path}Projects/personal/personal_8.png`,
      `${path}Projects/personal/personal_9.png`,
      `${path}Projects/personal/personal_10.png`,
      `${path}Projects/personal/personal_12.png`,
      `${path}Projects/personal/personal_12.png`,
      `${path}Projects/personal/personal_13.png`,
      `${path}Projects/personal/personal_14.png`,
      `${path}Projects/personal/personal_15.png`,
      `${path}Projects/personal/personal_16.png`,
      `${path}Projects/personal/personal_17.png`,
      `${path}Projects/personal/personal_18.png`,
      `${path}Projects/personal/personal_19.png`,
      `${path}Projects/personal.png`,
      `${path}Projects/personal_back.png`,
      `${path}Projects/personal_front.png`,
      `${path}Projects/pocketcare/pocketcare_0.png`,
      `${path}Projects/pocketcare/pocketcare_1.png`,
      `${path}Projects/pocketcare/pocketcare_2.png`,
      `${path}Projects/pocketcare/pocketcare_3.png`,
      `${path}Projects/pocketcare/pocketcare_4.png`,
      `${path}Projects/pocketcare/pocketcare_5.png`,
      `${path}Projects/pocketcare/pocketcare_6.png`,
      `${path}Projects/pocketcare/pocketcare_7.png`,
      `${path}Projects/pocketcare/pocketcare_8.png`,
      `${path}Projects/pocketcare/pocketcare_9.png`,
      `${path}Projects/pocketcare/pocketcare_10.png`,
      `${path}Projects/pocketcare/pocketcare_12.png`,
      `${path}Projects/pocketcare/pocketcare_12.png`,
      `${path}Projects/pocketcare/pocketcare_13.png`,
      `${path}Projects/pocketcare/pocketcare_14.png`,
      `${path}Projects/pocketcare/pocketcare_15.png`,
      `${path}Projects/pocketcare/pocketcare_16.png`,
      `${path}Projects/pocketcare/pocketcare_17.png`,
      `${path}Projects/pocketcare/pocketcare_18.png`,
      `${path}Projects/pocketcare/pocketcare_19.png`,
      `${path}Projects/pocketcare.png`,
      `${path}Projects/pocketcare_back.png`,
      `${path}Projects/pocketcare_extra.png`,
      `${path}Projects/pocketcare_front.png`,
      `${path}Projects/tesla/tesla_0.png`,
      `${path}Projects/tesla/tesla_1.png`,
      `${path}Projects/tesla/tesla_2.png`,
      `${path}Projects/tesla/tesla_3.png`,
      `${path}Projects/tesla/tesla_4.png`,
      `${path}Projects/tesla/tesla_5.png`,
      `${path}Projects/tesla/tesla_6.png`,
      `${path}Projects/tesla/tesla_7.png`,
      `${path}Projects/tesla/tesla_8.png`,
      `${path}Projects/tesla/tesla_9.png`,
      `${path}Projects/tesla/tesla_10.png`,
      `${path}Projects/tesla/tesla_12.png`,
      `${path}Projects/tesla/tesla_12.png`,
      `${path}Projects/tesla/tesla_13.png`,
      `${path}Projects/tesla/tesla_14.png`,
      `${path}Projects/tesla/tesla_15.png`,
      `${path}Projects/tesla/tesla_16.png`,
      `${path}Projects/tesla/tesla_17.png`,
      `${path}Projects/tesla/tesla_18.png`,
      `${path}Projects/tesla/tesla_19.png`,
      `${path}Projects/tesla.png`,
      `${path}Projects/tesla_back.png`,
      `${path}Projects/tesla_extra.png`,
      `${path}Projects/tesla_front.png`,

      `${path}Tesla/Car.png`,
      `${path}Tesla/Hand_1.png`,
      `${path}Tesla/Hand_2.png`,
      `${path}Tesla/Hand_3.png`,
      `${path}Tesla/Hand_4.png`,
      `${path}Tesla/Hand_5.png`,
      `${path}Tesla/Helmet.png`,
      `${path}Tesla/Logo_O.png`,
      `${path}Tesla/Logo_T.png`,
      `${path}Tesla/Logo_TO.png`,
      `${path}Tesla/Mobile_1.png`,
      `${path}Tesla/Mobile_2.png`,
      `${path}Tesla/Mobile_3.png`,
      `${path}Tesla/Mobile_4.png`,
      `${path}Tesla/Mobile_5.png`,
      `${path}Tesla/Mobile_6.png`,
      `${path}Tesla/Mobile_7.png`,
      `${path}Tesla/Mobile_8.png`,
      `${path}Tesla/Mobile_mockup.png`,
      `${path}Tesla/Phone_1-overflow_1.png`,
      `${path}Tesla/Phone_1-overflow_2.png`,
      `${path}Tesla/Phone_1-overflow_3.png`,
      `${path}Tesla/Phone_1.png`,
      `${path}Tesla/Phone_2-overflow_1.png`,
      `${path}Tesla/Phone_2-overflow_2.png`,
      `${path}Tesla/Phone_2-overflow_3.png`,
      `${path}Tesla/Phone_2.png`,
      `${path}Tesla/Phone_3.gif`,
      `${path}Tesla/Tablet_black_1.png`,
      `${path}Tesla/Tablet_black_2.png`,
      `${path}Tesla/Tablet_black_3.png`,
      `${path}Tesla/Tablet_black_4.png`,
      `${path}Tesla/Tablet_black_5.png`,
      `${path}Tesla/Tablet_black_6.png`,
      `${path}Tesla/Tablet_mockup.png`,
      `${path}Tesla/Tablet_white_1.png`,
      `${path}Tesla/Tablet_white_2.png`,
      `${path}Tesla/Tablet_white_3.png`,
      `${path}Tesla/Tablet_white_4.png`,
      `${path}Tesla/Tablet_white_5.png`,
      `${path}Tesla/Tablet_white_6.png`,
      `${path}Tesla/Watch.gif`,
      `${path}Tesla/Watches_1.png`,
      `${path}Tesla/Watches_2.png`
    ])
  }
}
</script>
